default_language_version:
  python: python3.11
repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files
        -   id: check-builtin-literals
        -   id: check-toml
        -   id: check-merge-conflict

    -   repo: https://github.com/pycqa/isort
        rev: 5.12.0
        hooks:
        -   id: isort
            name: isort (python)

    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.15.0
        hooks:
        -   id: pyupgrade

    -   repo: https://github.com/astral-sh/ruff-pre-commit
        rev: v0.1.6
        hooks:
          - id: ruff
#            args: [ --fix, --exit-non-zero-on-fix ]
          - id: ruff-format
